controller_manager_ns: controller_manager
controller_list:
  - name: car2_sld/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    # default: true
    default: false
    joints:
      - arm1_joint
      - arm2_joint
      - arm3_joint

  - name: car2_sld/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    # default: true
    default: false
    joints:
      - finger1_joint
      - finger2_joint

  
