controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm1_joint
      - arm2_joint
      - arm3_joint
      - hand_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger1_joint
      - finger2_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: home