

  


#arm_controller:
#  type: effort_controllers/JointTrajectoryController
#  joints:
#    - arm1_joint
#    - arm2_joint
#    - arm3_joint
#  gains:
#    arm1_joint:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    arm2_joint:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    arm3_joint:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#gripper_controller:
#  type: effort_controllers/JointTrajectoryController
#  joints:
#    - finger1_joint
#    - finger2_joint
#  gains:
#    finger1_joint:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    finger2_joint:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
